### ISSUE TITLE
Contribution to this project

### ISSUE THREAD

**Issue by gesinn-it** [exanion/zammad-js-api#4]
I'd like to contribute to this project. What's the branch policy? From _travis.yml_ I can see, that `master` is excluded but `dev` and other branches are included. Do you like to receive PRs in `dev`?

**Comment by peterkappelt** [comment]
This project is basically aboned from our site, unfortunately. However, contributions are always welcome!

Please work and developed in the `dev` branch (or sepearate feature branches). If all tests pass, a release branch is created by the `createRelease.sh` script that will publish to npm
